// Curated emoji list for the tab emoji picker (2026-09-07). Data only, so it is cheap to import: no
// functions, no imports. Each entry is [emoji, name, keywords], the name a CLDR short name in plain
// lowercase words (American spelling where CLDR's differs: the cell's tooltip shows the name, and the
// British form stays a keyword), the keywords a few extra lowercase words a person might type, separated
// by single spaces (the picker splits on spaces and matches word prefixes against name and keywords).
// Every emoji is one fully-qualified single emoji: a base with the U+FE0F presentation selector where
// the code point is text-default, a keycap, a flag (two regional indicators), or a joined (ZWJ) sequence.
// Skin-tone variants are out of scope (no U+1F3FB..U+1F3FF anywhere): the picker offers the neutral
// form, and the footer's free-text field takes any emoji the kernel accepts, toned ones included.
// Only emoji from Unicode 12.0 or earlier, so every entry draws on a several-years-old emoji font.
// The kernel's validator (kernel/kernel.py _emoji_check) stays the authority on what a tab accepts.
export type EmojiEntry = readonly [emoji: string, name: string, keywords: string];
export interface EmojiCategory { readonly id: string; readonly label: string; readonly icon: string; readonly items: readonly EmojiEntry[] }
export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  { id: "smileys", label: "Smileys", icon: "\u{1F600}", items: [
    ["\u{1F600}", "grinning face", "smile happy"],
    ["\u{1F603}", "grinning face with big eyes", "smile happy"],
    ["\u{1F604}", "grinning face with smiling eyes", "smile happy"],
    ["\u{1F601}", "beaming face with smiling eyes", "grin teeth"],
    ["\u{1F606}", "grinning squinting face", "laugh xd"],
    ["\u{1F605}", "grinning face with sweat", "nervous phew"],
    ["\u{1F923}", "rolling on the floor laughing", "rofl lol"],
    ["\u{1F602}", "face with tears of joy", "lol laugh cry"],
    ["\u{1F642}", "slightly smiling face", "smile"],
    ["\u{1F643}", "upside-down face", "silly sarcasm"],
    ["\u{1F609}", "winking face", "wink"],
    ["\u{1F60A}", "smiling face with smiling eyes", "blush happy"],
    ["\u{1F607}", "smiling face with halo", "angel innocent"],
    ["\u{1F970}", "smiling face with hearts", "love adore"],
    ["\u{1F60D}", "smiling face with heart-eyes", "love crush"],
    ["\u{1F929}", "star-struck", "wow starry eyes"],
    ["\u{1F618}", "face blowing a kiss", "kiss love"],
    ["\u{263A}\u{FE0F}", "smiling face", "relaxed"],
    ["\u{1F60B}", "face savoring food", "yum delicious"],
    ["\u{1F61C}", "winking face with tongue", "joke playful"],
    ["\u{1F911}", "money-mouth face", "rich dollar"],
    ["\u{1F917}", "hugging face", "hug"],
    ["\u{1F92B}", "shushing face", "quiet secret shh"],
    ["\u{1F914}", "thinking face", "hmm think"],
    ["\u{1F910}", "zipper-mouth face", "silence secret"],
    ["\u{1F928}", "face with raised eyebrow", "skeptical suspicious"],
    ["\u{1F610}", "neutral face", "meh blank"],
    ["\u{1F60F}", "smirking face", "smirk smug"],
    ["\u{1F612}", "unamused face", "meh annoyed"],
    ["\u{1F644}", "face with rolling eyes", "eye roll"],
    ["\u{1F62C}", "grimacing face", "awkward teeth"],
    ["\u{1F60C}", "relieved face", "calm relief"],
    ["\u{1F614}", "pensive face", "sad thoughtful"],
    ["\u{1F634}", "sleeping face", "zzz asleep"],
    ["\u{1F637}", "face with medical mask", "sick mask"],
    ["\u{1F912}", "face with thermometer", "sick ill fever"],
    ["\u{1F922}", "nauseated face", "sick green"],
    ["\u{1F92E}", "face vomiting", "sick puke"],
    ["\u{1F975}", "hot face", "heat sweating"],
    ["\u{1F976}", "cold face", "freezing"],
    ["\u{1F974}", "woozy face", "dizzy drunk"],
    ["\u{1F635}", "face with crossed-out eyes", "dizzy knocked out"],
    ["\u{1F92F}", "exploding head", "mind blown"],
    ["\u{1F920}", "cowboy hat face", "cowboy"],
    ["\u{1F973}", "partying face", "party celebrate"],
    ["\u{1F60E}", "smiling face with sunglasses", "cool"],
    ["\u{1F913}", "nerd face", "glasses geek"],
    ["\u{1F9D0}", "face with monocle", "inspect curious"],
    ["\u{1F615}", "confused face", "confused"],
    ["\u{1F641}", "slightly frowning face", "sad frown"],
    ["\u{2639}\u{FE0F}", "frowning face", "sad frown"],
    ["\u{1F62E}", "face with open mouth", "surprised wow"],
    ["\u{1F633}", "flushed face", "embarrassed blush"],
    ["\u{1F97A}", "pleading face", "puppy eyes beg"],
    ["\u{1F630}", "anxious face with sweat", "nervous"],
    ["\u{1F622}", "crying face", "sad tear"],
    ["\u{1F62D}", "loudly crying face", "sob bawling"],
    ["\u{1F631}", "face screaming in fear", "scream horror"],
    ["\u{1F61E}", "disappointed face", "sad"],
    ["\u{1F629}", "weary face", "tired"],
    ["\u{1F971}", "yawning face", "bored tired"],
    ["\u{1F624}", "face with steam from nose", "angry frustrated"],
    ["\u{1F621}", "pouting face", "angry mad"],
    ["\u{1F620}", "angry face", "mad"],
    ["\u{1F92C}", "face with symbols on mouth", "swearing cursing"],
    ["\u{1F608}", "smiling face with horns", "devil evil"],
    ["\u{1F480}", "skull", "dead death"],
    ["\u{2620}\u{FE0F}", "skull and crossbones", "danger poison"],
    ["\u{1F4A9}", "pile of poo", "poop"],
    ["\u{1F921}", "clown face", "clown"],
    ["\u{1F47B}", "ghost", "boo spooky"],
    ["\u{1F916}", "robot", "bot machine"],
    ["\u{1F47E}", "alien monster", "space invader game"],
    ["\u{1F63A}", "grinning cat", "cat smile"],
    ["\u{1F63B}", "smiling cat with heart-eyes", "cat love"],
    ["\u{1F648}", "see-no-evil monkey", "monkey hide"],
    ["\u{1F649}", "hear-no-evil monkey", "monkey ears"],
    ["\u{1F64A}", "speak-no-evil monkey", "monkey mouth"],
    ["\u{1F48B}", "kiss mark", "lips lipstick"],
    ["\u{1F498}", "heart with arrow", "cupid love"],
    ["\u{1F496}", "sparkling heart", "love"],
    ["\u{1F495}", "two hearts", "love"],
    ["\u{2763}\u{FE0F}", "heart exclamation", "love"],
    ["\u{1F494}", "broken heart", "heartbreak sad"],
    ["\u{1F4AF}", "hundred points", "100 perfect score"],
    ["\u{1F4A5}", "collision", "boom explosion bang"],
    ["\u{1F4AC}", "speech balloon", "comment chat talk"],
    ["\u{1F4AD}", "thought balloon", "thinking idea"],
    ["\u{1F4A4}", "zzz", "sleep snore"],
  ] },
  { id: "people", label: "People", icon: "\u{1F44B}", items: [
    ["\u{1F44B}", "waving hand", "hello bye wave"],
    ["\u{270B}", "raised hand", "stop high five"],
    ["\u{1F44C}", "ok hand", "okay perfect"],
    ["\u{1F90F}", "pinching hand", "small tiny"],
    ["\u{270C}\u{FE0F}", "victory hand", "peace two"],
    ["\u{1F91E}", "crossed fingers", "luck hope"],
    ["\u{1F91F}", "love-you gesture", "ily"],
    ["\u{1F918}", "sign of the horns", "rock metal"],
    ["\u{1F448}", "backhand index pointing left", "left"],
    ["\u{1F449}", "backhand index pointing right", "right"],
    ["\u{1F446}", "backhand index pointing up", "up"],
    ["\u{1F447}", "backhand index pointing down", "down"],
    ["\u{261D}\u{FE0F}", "index pointing up", "point"],
    ["\u{1F44D}", "thumbs up", "like yes approve"],
    ["\u{1F44E}", "thumbs down", "dislike no"],
    ["\u{270A}", "raised fist", "power punch"],
    ["\u{1F44A}", "oncoming fist", "punch bump"],
    ["\u{1F44F}", "clapping hands", "applause bravo"],
    ["\u{1F64C}", "raising hands", "hooray celebrate"],
    ["\u{1F91D}", "handshake", "deal agreement"],
    ["\u{1F64F}", "folded hands", "please thanks pray"],
    ["\u{270D}\u{FE0F}", "writing hand", "write pen"],
    ["\u{1F933}", "selfie", "camera phone"],
    ["\u{1F4AA}", "flexed biceps", "strong muscle"],
    ["\u{1F442}", "ear", "hear listen"],
    ["\u{1F9E0}", "brain", "smart mind think"],
    ["\u{1F440}", "eyes", "look watch see"],
    ["\u{1F441}\u{FE0F}", "eye", "look see"],
    ["\u{1F476}", "baby", "child infant"],
    ["\u{1F9D1}", "person", "adult"],
    ["\u{1F468}", "man", "guy"],
    ["\u{1F469}", "woman", "lady"],
    ["\u{1F46E}", "police officer", "cop"],
    ["\u{1F575}\u{FE0F}", "detective", "spy sleuth"],
    ["\u{1F477}", "construction worker", "builder hardhat"],
    ["\u{1F9D9}", "mage", "wizard witch"],
    ["\u{1F385}", "santa claus", "christmas"],
    ["\u{1F937}", "person shrugging", "shrug dunno"],
    ["\u{1F926}", "person facepalming", "facepalm"],
    ["\u{1F64B}", "person raising hand", "question volunteer"],
    ["\u{1F6B6}", "person walking", "walk"],
    ["\u{1F3C3}", "person running", "run"],
    ["\u{1F483}", "woman dancing", "dance"],
    ["\u{1F9D8}", "person in lotus position", "yoga meditate"],
    ["\u{1F469}\u{200D}\u{1F4BB}", "woman technologist", "coder programmer developer"],
    ["\u{1F468}\u{200D}\u{1F4BB}", "man technologist", "coder programmer developer"],
    ["\u{1F5E3}\u{FE0F}", "speaking head", "talk speak"],
    ["\u{1F464}", "bust in silhouette", "user profile"],
    ["\u{1F465}", "busts in silhouette", "users group team"],
    ["\u{1F9D1}\u{200D}\u{1F91D}\u{200D}\u{1F9D1}", "people holding hands", "friends pair"],
    ["\u{1F491}", "couple with heart", "love"],
    ["\u{1F46A}", "family", "parents kids"],
    ["\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}", "family man woman girl boy", "parents kids"],
    ["\u{1F463}", "footprints", "steps"],
  ] },
  { id: "animals", label: "Animals & nature", icon: "\u{1F43B}", items: [
    ["\u{1F436}", "dog face", "puppy pet"],
    ["\u{1F415}", "dog", "pet"],
    ["\u{1F98A}", "fox", "sly"],
    ["\u{1F99D}", "raccoon", "trash panda"],
    ["\u{1F431}", "cat face", "kitten pet"],
    ["\u{1F408}", "cat", "pet"],
    ["\u{1F981}", "lion", "roar"],
    ["\u{1F984}", "unicorn", "magic"],
    ["\u{1F993}", "zebra", "stripes"],
    ["\u{1F98C}", "deer", "antlers"],
    ["\u{1F42E}", "cow face", "moo"],
    ["\u{1F437}", "pig face", "oink"],
    ["\u{1F992}", "giraffe", "tall"],
    ["\u{1F418}", "elephant", "trunk"],
    ["\u{1F430}", "rabbit face", "bunny"],
    ["\u{1F987}", "bat", "vampire"],
    ["\u{1F43B}", "bear", "grizzly"],
    ["\u{1F428}", "koala", "australia"],
    ["\u{1F43C}", "panda", "bamboo"],
    ["\u{1F9A5}", "sloth", "slow lazy"],
    ["\u{1F43E}", "paw prints", "tracks"],
    ["\u{1F414}", "chicken", "hen"],
    ["\u{1F426}", "bird", "tweet"],
    ["\u{1F427}", "penguin", "cold"],
    ["\u{1F54A}\u{FE0F}", "dove", "peace"],
    ["\u{1F986}", "duck", "quack"],
    ["\u{1F989}", "owl", "wise night"],
    ["\u{1F9A9}", "flamingo", "pink"],
    ["\u{1F438}", "frog", "toad"],
    ["\u{1F40A}", "crocodile", "alligator"],
    ["\u{1F422}", "turtle", "tortoise slow"],
    ["\u{1F98E}", "lizard", "gecko"],
    ["\u{1F40D}", "snake", "python"],
    ["\u{1F409}", "dragon", "fantasy"],
    ["\u{1F996}", "t-rex", "dinosaur"],
    ["\u{1F433}", "spouting whale", "ocean"],
    ["\u{1F42C}", "dolphin", "ocean"],
    ["\u{1F41F}", "fish", "swim"],
    ["\u{1F988}", "shark", "ocean"],
    ["\u{1F419}", "octopus", "tentacles"],
    ["\u{1F40C}", "snail", "slow"],
    ["\u{1F98B}", "butterfly", "insect"],
    ["\u{1F41C}", "ant", "insect"],
    ["\u{1F41B}", "bug", "insect caterpillar"],
    ["\u{1F41E}", "lady beetle", "ladybug insect"],
    ["\u{1F41D}", "honeybee", "bee"],
    ["\u{1F577}\u{FE0F}", "spider", "web"],
    ["\u{1F9A0}", "microbe", "germ virus bacteria"],
    ["\u{1F490}", "bouquet", "flowers"],
    ["\u{1F338}", "cherry blossom", "sakura flower"],
    ["\u{1F339}", "rose", "flower"],
    ["\u{1F33B}", "sunflower", "flower"],
    ["\u{1F337}", "tulip", "flower"],
    ["\u{1F331}", "seedling", "sprout plant"],
    ["\u{1F332}", "evergreen tree", "pine"],
    ["\u{1F333}", "deciduous tree", "tree"],
    ["\u{1F334}", "palm tree", "beach"],
    ["\u{1F335}", "cactus", "desert"],
    ["\u{2618}\u{FE0F}", "shamrock", "irish"],
    ["\u{1F340}", "four leaf clover", "luck"],
    ["\u{1F341}", "maple leaf", "autumn canada"],
    ["\u{1F343}", "leaf fluttering in wind", "leaves"],
    ["\u{1F319}", "crescent moon", "night"],
    ["\u{1F315}", "full moon", "night"],
    ["\u{2600}\u{FE0F}", "sun", "sunny weather"],
    ["\u{1F31E}", "sun with face", "sunny"],
    ["\u{2B50}", "star", "favorite"],
    ["\u{1F31F}", "glowing star", "shining"],
    ["\u{1F320}", "shooting star", "wish"],
    ["\u{26C5}", "sun behind cloud", "partly cloudy weather"],
    ["\u{2601}\u{FE0F}", "cloud", "weather overcast"],
    ["\u{1F327}\u{FE0F}", "cloud with rain", "rainy weather"],
    ["\u{26C8}\u{FE0F}", "cloud with lightning and rain", "thunderstorm storm"],
    ["\u{26A1}", "high voltage", "lightning electric zap"],
    ["\u{2744}\u{FE0F}", "snowflake", "snow cold winter"],
    ["\u{1F525}", "fire", "flame hot lit"],
    ["\u{1F4A7}", "droplet", "water drop"],
    ["\u{1F30A}", "water wave", "ocean sea surf"],
    ["\u{1F308}", "rainbow", "pride colors"],
    ["\u{2614}", "umbrella with rain drops", "rain"],
    ["\u{1F300}", "cyclone", "hurricane swirl"],
  ] },
  { id: "food", label: "Food & drink", icon: "\u{1F34E}", items: [
    ["\u{1F347}", "grapes", "fruit wine"],
    ["\u{1F349}", "watermelon", "fruit summer"],
    ["\u{1F34A}", "tangerine", "orange mandarin fruit"],
    ["\u{1F34B}", "lemon", "citrus sour"],
    ["\u{1F34C}", "banana", "fruit"],
    ["\u{1F34D}", "pineapple", "fruit tropical"],
    ["\u{1F96D}", "mango", "fruit tropical"],
    ["\u{1F34E}", "red apple", "fruit"],
    ["\u{1F34F}", "green apple", "fruit"],
    ["\u{1F351}", "peach", "fruit"],
    ["\u{1F352}", "cherries", "fruit"],
    ["\u{1F353}", "strawberry", "fruit berry"],
    ["\u{1F345}", "tomato", "vegetable"],
    ["\u{1F951}", "avocado", "guacamole"],
    ["\u{1F346}", "eggplant", "aubergine vegetable"],
    ["\u{1F955}", "carrot", "vegetable"],
    ["\u{1F33D}", "ear of corn", "maize vegetable"],
    ["\u{1F336}\u{FE0F}", "hot pepper", "chili spicy"],
    ["\u{1F966}", "broccoli", "vegetable"],
    ["\u{1F344}", "mushroom", "fungus"],
    ["\u{1F35E}", "bread", "loaf toast"],
    ["\u{1F950}", "croissant", "pastry french"],
    ["\u{1F956}", "baguette bread", "french"],
    ["\u{1F95E}", "pancakes", "breakfast"],
    ["\u{1F9C7}", "waffle", "breakfast"],
    ["\u{1F9C0}", "cheese wedge", "cheese"],
    ["\u{1F969}", "cut of meat", "steak"],
    ["\u{1F354}", "hamburger", "burger fast food"],
    ["\u{1F35F}", "french fries", "chips fast food"],
    ["\u{1F355}", "pizza", "slice"],
    ["\u{1F32D}", "hot dog", "sausage"],
    ["\u{1F96A}", "sandwich", "lunch"],
    ["\u{1F32E}", "taco", "mexican"],
    ["\u{1F95A}", "egg", "breakfast"],
    ["\u{1F373}", "cooking", "fried egg frying pan"],
    ["\u{1F372}", "pot of food", "stew soup"],
    ["\u{1F957}", "green salad", "healthy"],
    ["\u{1F37F}", "popcorn", "movie snack"],
    ["\u{1F371}", "bento box", "japanese lunch"],
    ["\u{1F35C}", "steaming bowl", "ramen noodles"],
    ["\u{1F35D}", "spaghetti", "pasta noodles"],
    ["\u{1F363}", "sushi", "japanese"],
    ["\u{1F95F}", "dumpling", "gyoza"],
    ["\u{1F980}", "crab", "seafood"],
    ["\u{1F990}", "shrimp", "prawn seafood"],
    ["\u{1F368}", "ice cream", "dessert"],
    ["\u{1F369}", "donut", "doughnut dessert"],
    ["\u{1F36A}", "cookie", "biscuit dessert"],
    ["\u{1F382}", "birthday cake", "celebrate party"],
    ["\u{1F9C1}", "cupcake", "dessert"],
    ["\u{1F967}", "pie", "dessert"],
    ["\u{1F36B}", "chocolate bar", "candy sweet"],
    ["\u{1F36C}", "candy", "sweet"],
    ["\u{1F36D}", "lollipop", "candy sweet"],
    ["\u{2615}", "hot beverage", "coffee tea cup"],
    ["\u{1F375}", "teacup without handle", "green tea"],
    ["\u{1F37E}", "bottle with popping cork", "champagne celebrate"],
    ["\u{1F377}", "wine glass", "red white drink"],
    ["\u{1F378}", "cocktail glass", "martini drink"],
    ["\u{1F37A}", "beer mug", "drink pint"],
    ["\u{1F37B}", "clinking beer mugs", "cheers drink"],
    ["\u{1F942}", "clinking glasses", "cheers toast"],
    ["\u{1F9CA}", "ice", "cube cold"],
    ["\u{1F374}", "fork and knife", "eat cutlery"],
  ] },
  { id: "travel", label: "Travel & places", icon: "\u{1F697}", items: [
    ["\u{1F30D}", "globe showing europe-africa", "earth world"],
    ["\u{1F30E}", "globe showing americas", "earth world"],
    ["\u{1F30F}", "globe showing asia-australia", "earth world"],
    ["\u{1F310}", "globe with meridians", "internet web world"],
    ["\u{1F5FA}\u{FE0F}", "world map", "atlas"],
    ["\u{1F9ED}", "compass", "navigation direction"],
    ["\u{1F3D4}\u{FE0F}", "snow-capped mountain", "peak"],
    ["\u{26F0}\u{FE0F}", "mountain", "hill"],
    ["\u{1F30B}", "volcano", "eruption lava"],
    ["\u{1F3D5}\u{FE0F}", "camping", "tent outdoors"],
    ["\u{1F3D6}\u{FE0F}", "beach with umbrella", "vacation"],
    ["\u{1F3E0}", "house", "home"],
    ["\u{1F3E1}", "house with garden", "home"],
    ["\u{1F3E2}", "office building", "work"],
    ["\u{1F3E5}", "hospital", "medical"],
    ["\u{1F3EB}", "school", "education"],
    ["\u{1F3ED}", "factory", "industry"],
    ["\u{1F3F0}", "castle", "fortress"],
    ["\u{1F5FC}", "tokyo tower", "japan"],
    ["\u{1F5FD}", "statue of liberty", "new york"],
    ["\u{26EA}", "church", "chapel"],
    ["\u{1F54C}", "mosque", "islam"],
    ["\u{1F3D9}\u{FE0F}", "cityscape", "city skyline"],
    ["\u{1F307}", "sunset", "evening"],
    ["\u{1F3A1}", "ferris wheel", "amusement"],
    ["\u{1F682}", "locomotive", "steam train"],
    ["\u{1F686}", "train", "rail"],
    ["\u{1F687}", "metro", "subway underground"],
    ["\u{1F68C}", "bus", "transit"],
    ["\u{1F691}", "ambulance", "emergency"],
    ["\u{1F692}", "fire engine", "truck"],
    ["\u{1F693}", "police car", "cop"],
    ["\u{1F697}", "automobile", "car"],
    ["\u{1F699}", "sport utility vehicle", "suv jeep"],
    ["\u{1F69A}", "delivery truck", "shipping"],
    ["\u{1F3CE}\u{FE0F}", "racing car", "formula speed"],
    ["\u{1F3CD}\u{FE0F}", "motorcycle", "bike"],
    ["\u{1F9BD}", "manual wheelchair", "accessibility"],
    ["\u{1F6B2}", "bicycle", "bike cycling"],
    ["\u{26FD}", "fuel pump", "gas petrol"],
    ["\u{1F6A8}", "police car light", "siren alert emergency"],
    ["\u{1F6D1}", "stop sign", "halt"],
    ["\u{1F6A7}", "construction", "barrier roadwork"],
    ["\u{2693}", "anchor", "harbor"],
    ["\u{26F5}", "sailboat", "sailing yacht"],
    ["\u{1F6F3}\u{FE0F}", "passenger ship", "cruise"],
    ["\u{1F6A2}", "ship", "boat"],
    ["\u{2708}\u{FE0F}", "airplane", "flight travel"],
    ["\u{1F6E9}\u{FE0F}", "small airplane", "plane flight"],
    ["\u{1F6EB}", "airplane departure", "takeoff"],
    ["\u{1F6EC}", "airplane arrival", "landing"],
    ["\u{1FA82}", "parachute", "skydive"],
    ["\u{1F681}", "helicopter", "chopper"],
    ["\u{1F6F0}\u{FE0F}", "satellite", "orbit space"],
    ["\u{1F680}", "rocket", "launch ship space"],
    ["\u{1F6F8}", "flying saucer", "ufo alien"],
    ["\u{1F9F3}", "luggage", "suitcase travel"],
    ["\u{23F3}", "hourglass not done", "time waiting"],
    ["\u{231B}", "hourglass done", "time finished elapsed timeout"],
    ["\u{23F1}\u{FE0F}", "stopwatch", "timer time"],
    ["\u{231A}", "watch", "time wrist"],
    ["\u{23F0}", "alarm clock", "time wake"],
  ] },
  { id: "activities", label: "Activities", icon: "\u{26BD}", items: [
    ["\u{1F383}", "jack-o-lantern", "halloween pumpkin"],
    ["\u{1F384}", "christmas tree", "holiday"],
    ["\u{1F386}", "fireworks", "celebration"],
    ["\u{2728}", "sparkles", "shiny new magic"],
    ["\u{1F388}", "balloon", "party"],
    ["\u{1F389}", "party popper", "celebrate tada"],
    ["\u{1F38A}", "confetti ball", "party celebrate"],
    ["\u{1F380}", "ribbon", "bow"],
    ["\u{1F381}", "wrapped gift", "present"],
    ["\u{1F3C6}", "trophy", "win award champion"],
    ["\u{1F947}", "1st place medal", "gold first winner"],
    ["\u{1F948}", "2nd place medal", "silver second"],
    ["\u{1F949}", "3rd place medal", "bronze third"],
    ["\u{26BD}", "soccer ball", "football sport"],
    ["\u{26BE}", "baseball", "sport"],
    ["\u{1F3C0}", "basketball", "sport"],
    ["\u{1F3D0}", "volleyball", "sport"],
    ["\u{1F3C8}", "american football", "sport"],
    ["\u{1F3BE}", "tennis", "racket sport"],
    ["\u{1F3B3}", "bowling", "pins"],
    ["\u{1F3D3}", "ping pong", "table tennis"],
    ["\u{1F94A}", "boxing glove", "fight"],
    ["\u{26F3}", "flag in hole", "golf"],
    ["\u{1F3BF}", "skis", "skiing snow"],
    ["\u{1F3AF}", "direct hit", "bullseye target goal"],
    ["\u{1F52E}", "crystal ball", "fortune magic"],
    ["\u{1F3AE}", "video game", "controller gaming"],
    ["\u{1F579}\u{FE0F}", "joystick", "arcade"],
    ["\u{1F3B2}", "game die", "dice random"],
    ["\u{1F9E9}", "puzzle piece", "jigsaw"],
    ["\u{2660}\u{FE0F}", "spade suit", "cards"],
    ["\u{1F3AD}", "performing arts", "theater masks drama"],
    ["\u{1F3A8}", "artist palette", "paint art"],
    ["\u{1F3C4}", "person surfing", "surf"],
    ["\u{1F3CA}", "person swimming", "swim"],
    ["\u{1F6B4}", "person biking", "cycling"],
    ["\u{1F3CB}\u{FE0F}", "person lifting weights", "gym workout"],
    ["\u{1F3A4}", "microphone", "karaoke sing"],
    ["\u{1F3A7}", "headphone", "music"],
    ["\u{1F3B5}", "musical note", "music"],
    ["\u{1F3B6}", "musical notes", "music song"],
    ["\u{1F3B8}", "guitar", "music"],
    ["\u{1F3B9}", "musical keyboard", "piano"],
    ["\u{1F941}", "drum", "music"],
    ["\u{1F3B7}", "saxophone", "jazz"],
  ] },
  { id: "objects", label: "Objects", icon: "\u{1F4A1}", items: [
    ["\u{1F453}", "glasses", "eyeglasses"],
    ["\u{1F576}\u{FE0F}", "sunglasses", "shades"],
    ["\u{1F455}", "t-shirt", "shirt clothes"],
    ["\u{1F392}", "backpack", "school bag"],
    ["\u{1F451}", "crown", "king queen royal"],
    ["\u{1F393}", "graduation cap", "school degree"],
    ["\u{1F48E}", "gem stone", "diamond jewel"],
    ["\u{1F50A}", "speaker high volume", "loud sound"],
    ["\u{1F4E2}", "loudspeaker", "announcement"],
    ["\u{1F4E3}", "megaphone", "announce shout"],
    ["\u{1F514}", "bell", "notification alert"],
    ["\u{1F515}", "bell with slash", "mute silent quiet"],
    ["\u{1F4F1}", "mobile phone", "smartphone cell"],
    ["\u{1F50B}", "battery", "power charge"],
    ["\u{1F4BB}", "laptop", "computer notebook"],
    ["\u{1F5A5}\u{FE0F}", "desktop computer", "monitor pc"],
    ["\u{2328}\u{FE0F}", "keyboard", "typing"],
    ["\u{1F4BE}", "floppy disk", "save"],
    ["\u{1F3AC}", "clapper board", "movie action film"],
    ["\u{1F4F7}", "camera", "photo picture"],
    ["\u{1F50D}", "magnifying glass tilted left", "search find zoom"],
    ["\u{1F50E}", "magnifying glass tilted right", "search find zoom"],
    ["\u{1F56F}\u{FE0F}", "candle", "light"],
    ["\u{1F4A1}", "light bulb", "idea"],
    ["\u{1F4D6}", "open book", "read"],
    ["\u{1F4DA}", "books", "library read study"],
    ["\u{1F4C4}", "page facing up", "document file"],
    ["\u{1F4F0}", "newspaper", "news press"],
    ["\u{1F3F7}\u{FE0F}", "label", "tag"],
    ["\u{1F4B0}", "money bag", "cash rich"],
    ["\u{1F4B8}", "money with wings", "spend cost"],
    ["\u{1F4B3}", "credit card", "payment"],
    ["\u{2709}\u{FE0F}", "envelope", "mail letter"],
    ["\u{1F4E4}", "outbox tray", "send export"],
    ["\u{1F4E5}", "inbox tray", "receive import"],
    ["\u{1F4E6}", "package", "box parcel shipping"],
    ["\u{1F5C4}\u{FE0F}", "file cabinet", "archive storage"],
    ["\u{1F4E1}", "satellite antenna", "signal broadcast"],
    ["\u{270F}\u{FE0F}", "pencil", "write"],
    ["\u{1F58A}\u{FE0F}", "pen", "write"],
    ["\u{1F4DD}", "memo", "note write"],
    ["\u{1F4BC}", "briefcase", "work business"],
    ["\u{1F4C1}", "file folder", "directory"],
    ["\u{1F4C5}", "calendar", "date"],
    ["\u{1F4C8}", "chart increasing", "graph up growth"],
    ["\u{1F4C9}", "chart decreasing", "graph down loss"],
    ["\u{1F4CA}", "bar chart", "graph stats"],
    ["\u{1F4CB}", "clipboard", "list"],
    ["\u{1F4CC}", "pushpin", "pin"],
    ["\u{1F4CD}", "round pushpin", "location pin"],
    ["\u{1F4CE}", "paperclip", "attachment"],
    ["\u{1F516}", "bookmark", "save mark tag"],
    ["\u{2702}\u{FE0F}", "scissors", "cut"],
    ["\u{1F5D1}\u{FE0F}", "wastebasket", "trash delete"],
    ["\u{1F512}", "locked", "lock secure private"],
    ["\u{1F513}", "unlocked", "unlock open public"],
    ["\u{1F511}", "key", "password unlock"],
    ["\u{1F528}", "hammer", "tool build"],
    ["\u{1F6E0}\u{FE0F}", "hammer and wrench", "tools fix build"],
    ["\u{1F9F0}", "toolbox", "tools kit"],
    ["\u{1F9F9}", "broom", "sweep clean"],
    ["\u{1F9F1}", "brick", "wall build"],
    ["\u{1F6E1}\u{FE0F}", "shield", "protect security"],
    ["\u{1F4A3}", "bomb", "explosive boom danger"],
    ["\u{1F527}", "wrench", "tool fix"],
    ["\u{2699}\u{FE0F}", "gear", "settings config cog"],
    ["\u{2696}\u{FE0F}", "balance scale", "justice law"],
    ["\u{1F517}", "link", "chain url"],
    ["\u{1F9F2}", "magnet", "attract"],
    ["\u{1F9EA}", "test tube", "experiment lab"],
    ["\u{1F9EC}", "dna", "genetics"],
    ["\u{1F52C}", "microscope", "science lab"],
    ["\u{1F489}", "syringe", "needle vaccine"],
    ["\u{1F48A}", "pill", "medicine"],
    ["\u{1F6CF}\u{FE0F}", "bed", "sleep"],
    ["\u{1FA91}", "chair", "seat"],
    ["\u{1F9FC}", "soap", "clean wash"],
    ["\u{1F6D2}", "shopping cart", "trolley buy"],
    ["\u{1F5FF}", "moai", "statue"],
  ] },
  { id: "symbols", label: "Symbols", icon: "\u{2764}\u{FE0F}", items: [
    ["\u{2764}\u{FE0F}", "red heart", "love like"],
    ["\u{1F9E1}", "orange heart", "love"],
    ["\u{1F49B}", "yellow heart", "love"],
    ["\u{1F49A}", "green heart", "love"],
    ["\u{1F499}", "blue heart", "love"],
    ["\u{1F49C}", "purple heart", "love"],
    ["\u{1F90E}", "brown heart", "love"],
    ["\u{1F5A4}", "black heart", "love dark"],
    ["\u{1F90D}", "white heart", "love"],
    ["\u{26A0}\u{FE0F}", "warning", "caution alert"],
    ["\u{26D4}", "no entry", "forbidden stop"],
    ["\u{1F6AB}", "prohibited", "forbidden banned no"],
    ["\u{2B06}\u{FE0F}", "up arrow", "north"],
    ["\u{27A1}\u{FE0F}", "right arrow", "east next"],
    ["\u{2B07}\u{FE0F}", "down arrow", "south"],
    ["\u{2B05}\u{FE0F}", "left arrow", "west back"],
    ["\u{21A9}\u{FE0F}", "right arrow curving left", "return reply undo"],
    ["\u{1F504}", "counterclockwise arrows button", "refresh sync reload"],
    ["\u{262F}\u{FE0F}", "yin yang", "balance"],
    ["\u{2648}", "aries", "zodiac"],
    ["\u{2649}", "taurus", "zodiac"],
    ["\u{264A}", "gemini", "zodiac"],
    ["\u{264B}", "cancer", "zodiac"],
    ["\u{264C}", "leo", "zodiac"],
    ["\u{264D}", "virgo", "zodiac"],
    ["\u{264E}", "libra", "zodiac"],
    ["\u{264F}", "scorpio", "zodiac"],
    ["\u{2650}", "sagittarius", "zodiac"],
    ["\u{2651}", "capricorn", "zodiac"],
    ["\u{2652}", "aquarius", "zodiac"],
    ["\u{2653}", "pisces", "zodiac"],
    ["\u{25B6}\u{FE0F}", "play button", "start run"],
    ["\u{23F8}\u{FE0F}", "pause button", "wait"],
    ["\u{23F9}\u{FE0F}", "stop button", "halt"],
    ["\u{1F501}", "repeat button", "loop"],
    ["\u{1F195}", "new button", "new"],
    ["\u{1F51D}", "top arrow", "top up"],
    ["\u{267B}\u{FE0F}", "recycling symbol", "recycle"],
    ["\u{2705}", "check mark button", "done yes complete"],
    ["\u{2611}\u{FE0F}", "check box with check", "done todo"],
    ["\u{2714}\u{FE0F}", "check mark", "done yes tick"],
    ["\u{2716}\u{FE0F}", "multiply", "x times cancel"],
    ["\u{274C}", "cross mark", "x no wrong delete"],
    ["\u{274E}", "cross mark button", "x no wrong green"],
    ["\u{2795}", "plus", "add"],
    ["\u{2796}", "minus", "subtract remove"],
    ["\u{2733}\u{FE0F}", "eight-spoked asterisk", "star wildcard note"],
    ["\u{2753}", "red question mark", "question help"],
    ["\u{2757}", "red exclamation mark", "important alert"],
    ["\u{23}\u{FE0F}\u{20E3}", "keycap number sign", "hash pound"],
    ["\u{30}\u{FE0F}\u{20E3}", "keycap 0", "zero number"],
    ["\u{31}\u{FE0F}\u{20E3}", "keycap 1", "one number"],
    ["\u{32}\u{FE0F}\u{20E3}", "keycap 2", "two number"],
    ["\u{33}\u{FE0F}\u{20E3}", "keycap 3", "three number"],
    ["\u{34}\u{FE0F}\u{20E3}", "keycap 4", "four number"],
    ["\u{35}\u{FE0F}\u{20E3}", "keycap 5", "five number"],
    ["\u{36}\u{FE0F}\u{20E3}", "keycap 6", "six number"],
    ["\u{37}\u{FE0F}\u{20E3}", "keycap 7", "seven number"],
    ["\u{38}\u{FE0F}\u{20E3}", "keycap 8", "eight number"],
    ["\u{39}\u{FE0F}\u{20E3}", "keycap 9", "nine number"],
    ["\u{1F51F}", "keycap 10", "ten number"],
    ["\u{2139}\u{FE0F}", "information", "info help"],
    ["\u{1F197}", "ok button", "okay"],
    ["\u{1F198}", "sos button", "help emergency"],
    ["\u{1F534}", "red circle", "dot status"],
    ["\u{1F7E0}", "orange circle", "dot status"],
    ["\u{1F7E1}", "yellow circle", "dot status progress"],
    ["\u{1F7E2}", "green circle", "dot status"],
    ["\u{1F535}", "blue circle", "dot status"],
    ["\u{1F7E3}", "purple circle", "dot status"],
    ["\u{1F7E4}", "brown circle", "dot status"],
    ["\u{26AB}", "black circle", "dot status"],
    ["\u{26AA}", "white circle", "dot status"],
    ["\u{1F7E5}", "red square", "block"],
    ["\u{1F7E7}", "orange square", "block"],
    ["\u{1F7E8}", "yellow square", "block"],
    ["\u{1F7E9}", "green square", "block"],
    ["\u{1F7E6}", "blue square", "block"],
    ["\u{1F7EA}", "purple square", "block"],
    ["\u{1F7EB}", "brown square", "block"],
    ["\u{2B1B}", "black large square", "block"],
    ["\u{2B1C}", "white large square", "block"],
  ] },
  { id: "flags", label: "Flags", icon: "\u{1F3C1}", items: [
    ["\u{1F3C1}", "checkered flag", "chequered race finish done"],
    ["\u{1F6A9}", "triangular flag", "marker"],
    ["\u{1F38C}", "crossed flags", "japan"],
    ["\u{1F3F4}", "black flag", "dark"],
    ["\u{1F3F3}\u{FE0F}", "white flag", "surrender"],
    ["\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}", "rainbow flag", "pride lgbt"],
    ["\u{1F3F4}\u{200D}\u{2620}\u{FE0F}", "pirate flag", "jolly roger skull"],
    ["\u{1F1FA}\u{1F1F8}", "flag united states", "usa america us"],
    ["\u{1F1E8}\u{1F1E6}", "flag canada", "ca maple"],
    ["\u{1F1F2}\u{1F1FD}", "flag mexico", "mx"],
    ["\u{1F1E7}\u{1F1F7}", "flag brazil", "br"],
    ["\u{1F1EC}\u{1F1E7}", "flag united kingdom", "uk gb britain british"],
    ["\u{1F1EB}\u{1F1F7}", "flag france", "fr"],
    ["\u{1F1E9}\u{1F1EA}", "flag germany", "de deutschland"],
    ["\u{1F1EA}\u{1F1F8}", "flag spain", "es"],
    ["\u{1F1EE}\u{1F1F9}", "flag italy", "it"],
    ["\u{1F1F3}\u{1F1F1}", "flag netherlands", "nl holland dutch"],
    ["\u{1F1F8}\u{1F1EA}", "flag sweden", "se"],
    ["\u{1F1FA}\u{1F1E6}", "flag ukraine", "ua"],
    ["\u{1F1F7}\u{1F1FA}", "flag russia", "ru"],
    ["\u{1F1EE}\u{1F1F3}", "flag india", "in"],
    ["\u{1F1E8}\u{1F1F3}", "flag china", "cn"],
    ["\u{1F1EF}\u{1F1F5}", "flag japan", "jp nippon"],
    ["\u{1F1F0}\u{1F1F7}", "flag south korea", "kr"],
    ["\u{1F1EE}\u{1F1E9}", "flag indonesia", "id"],
    ["\u{1F1E6}\u{1F1FA}", "flag australia", "au"],
    ["\u{1F1F3}\u{1F1EC}", "flag nigeria", "ng"],
    ["\u{1F1FF}\u{1F1E6}", "flag south africa", "za"],
    ["\u{1F1EA}\u{1F1EC}", "flag egypt", "eg"],
    ["\u{1F1EA}\u{1F1FA}", "flag european union", "eu europe"],
    ["\u{1F1FA}\u{1F1F3}", "flag united nations", "un"],
  ] },
];
